// <auto-generated />
using System;
using DevExpressCountryManager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevExpressCountryManager.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20210318092912_AddFlagImages")]
    partial class AddFlagImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevExpressCountryManager.Models.Common.BlobbableImage", b =>
                {
                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ImagePath");

                    b.ToTable("BlobbableImages");
                });

            modelBuilder.Entity("DevExpressCountryManager.Models.WorldData.DXCountry", b =>
                {
                    b.Property<string>("Tag")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Allegiance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagImagePath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Government")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tag");

                    b.HasIndex("FlagImagePath");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DevExpressCountryManager.Models.WorldData.DXCountry", b =>
                {
                    b.HasOne("DevExpressCountryManager.Models.Common.BlobbableImage", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagImagePath");

                    b.Navigation("Flag");
                });
#pragma warning restore 612, 618
        }
    }
}
